/*
 * IssueObject.h -- IhiIssue, the GObject a list row is built from.
 *
 * GtkListBox is bound to a GListModel (a GListStore of these) rather than being
 * filled with hand-made rows, so every row has a stable identity: the issue's
 * uuid, carried by the object itself. Nothing anywhere in this app addresses an
 * issue by its position in an array.
 *
 * This deliberately does NOT hold an issueskit::Issue. A GObject instance
 * struct is allocated and freed by GObject, which neither constructs nor
 * destructs C++ members, so a std::string field here would be undefined
 * behaviour without placement-new plumbing in init/finalize. The authoritative
 * model stays in MainWindow; this carries only the five values a row draws,
 * as plain C strings and enums.
 */
#ifndef IHAVEISSUES_ISSUE_OBJECT_H
#define IHAVEISSUES_ISSUE_OBJECT_H

#include <glib-object.h>

#include <issueskit/IssueEnums.h>
#include <issueskit/IssueModel.h>

#define IHI_TYPE_ISSUE (ihi_issue_get_type())

G_DECLARE_FINAL_TYPE(IhiIssue, ihi_issue, IHI, ISSUE, GObject)

/*!	Snapshots \a issue for display.

	\return A new reference the caller owns. Appending it to a GListStore with
		g_list_store_append() does NOT consume that reference, so the usual
		call site is append-then-unref (or a g_autoptr).
*/
IhiIssue* ihi_issue_new(const issueskit::Issue& issue);

//! The stable identity: the issue's uuid. Owned by \a self.
const char* ihi_issue_get_uuid(IhiIssue* self);

//! The title as Pango markup -- bold, escaped, "Untitled" when blank.
const char* ihi_issue_get_title_markup(IhiIssue* self);

//! "#007".
const char* ihi_issue_get_number_text(IhiIssue* self);

/*  Not "ihi_issue_get_type": that name belongs to the GType registration
	function generated by G_DECLARE_FINAL_TYPE. */
issueskit::IssueType ihi_issue_get_kind(IhiIssue* self);
issueskit::IssuePriority ihi_issue_get_priority(IhiIssue* self);

#endif // IHAVEISSUES_ISSUE_OBJECT_H
